import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Homepage Modules — if you want to view the source, visit the plugin repository.
*/
`;

const prod = process.argv[2] === "production";

// Optional: set HM_OUT to a test vault's plugin folder to dev-load directly.
// e.g. HM_OUT="C:/TestVault/.obsidian/plugins/homepage-modules"
const outDir = process.env.HM_OUT || ".";

const copyStatics = {
  name: "copy-statics",
  setup(build) {
    build.onEnd(() => {
      if (outDir === ".") return;
      try {
        fs.mkdirSync(outDir, { recursive: true });
        for (const f of ["manifest.json", "styles.css", "wordbank-full.json"]) {
          if (fs.existsSync(f)) fs.copyFileSync(f, path.join(outDir, f));
        }
      } catch (e) {
        console.warn("copy-statics failed:", e.message);
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outDir, "main.js"),
  minify: prod,
  plugins: [copyStatics],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
