export interface WordEntry {
  word: string;
  reading?: string;
  meaning: string;
}

export interface WordLevel {
  id: string;
  name: string;
  words: WordEntry[];
}

/* 简写工具：w("word","/ipa/","释义") */
function w(word: string, reading: string, meaning: string): WordEntry {
  return { word, reading, meaning };
}

/**
 * 内置离线分级词库（英 → 中），全部本地、不联网。
 * 四个等级共约 360 词，可继续往各 level 追加或新增 level。
 */
export const LEVELS: WordLevel[] = [
  {
    id: "cet4",
    name: "四级核心",
    words: [
      w("abandon", "/əˈbændən/", "v. 抛弃，放弃"),
      w("ability", "/əˈbɪləti/", "n. 能力，才能"),
      w("absorb", "/əbˈzɔːb/", "v. 吸收，理解"),
      w("abstract", "/ˈæbstrækt/", "adj. 抽象的 n. 摘要"),
      w("accomplish", "/əˈkʌmplɪʃ/", "v. 完成，实现"),
      w("accurate", "/ˈækjərət/", "adj. 准确的"),
      w("acquire", "/əˈkwaɪə/", "v. 获得，习得"),
      w("adequate", "/ˈædɪkwət/", "adj. 足够的，适当的"),
      w("adjust", "/əˈdʒʌst/", "v. 调整，适应"),
      w("advantage", "/ədˈvɑːntɪdʒ/", "n. 优势，好处"),
      w("affect", "/əˈfekt/", "v. 影响"),
      w("annual", "/ˈænjuəl/", "adj. 每年的 n. 年刊"),
      w("apparent", "/əˈpærənt/", "adj. 明显的，表面的"),
      w("appreciate", "/əˈpriːʃieɪt/", "v. 欣赏，感激"),
      w("approach", "/əˈprəʊtʃ/", "v. 接近 n. 方法"),
      w("appropriate", "/əˈprəʊpriət/", "adj. 适当的"),
      w("approximately", "/əˈprɒksɪmətli/", "adv. 大约"),
      w("attitude", "/ˈætɪtjuːd/", "n. 态度"),
      w("attract", "/əˈtrækt/", "v. 吸引"),
      w("available", "/əˈveɪləbl/", "adj. 可获得的，可用的"),
      w("benefit", "/ˈbenɪfɪt/", "n. 益处 v. 受益"),
      w("calculate", "/ˈkælkjuleɪt/", "v. 计算"),
      w("capacity", "/kəˈpæsəti/", "n. 容量，能力"),
      w("category", "/ˈkætəɡəri/", "n. 类别"),
      w("circumstance", "/ˈsɜːkəmstæns/", "n. 环境，情况"),
      w("complex", "/ˈkɒmpleks/", "adj. 复杂的 n. 综合体"),
      w("conclude", "/kənˈkluːd/", "v. 得出结论，结束"),
      w("consequence", "/ˈkɒnsɪkwəns/", "n. 后果"),
      w("consume", "/kənˈsjuːm/", "v. 消耗，消费"),
      w("contribute", "/kənˈtrɪbjuːt/", "v. 贡献，促成"),
      w("convince", "/kənˈvɪns/", "v. 说服，使信服"),
      w("deliberate", "/dɪˈlɪbərət/", "adj. 故意的，深思熟虑的"),
      w("demonstrate", "/ˈdemənstreɪt/", "v. 证明，演示"),
      w("dependent", "/dɪˈpendənt/", "adj. 依赖的"),
      w("describe", "/dɪˈskraɪb/", "v. 描述"),
      w("device", "/dɪˈvaɪs/", "n. 装置，设备"),
      w("distinguish", "/dɪˈstɪŋɡwɪʃ/", "v. 区分，辨别"),
      w("efficient", "/ɪˈfɪʃnt/", "adj. 高效的"),
      w("eliminate", "/ɪˈlɪmɪneɪt/", "v. 消除，淘汰"),
      w("emphasize", "/ˈemfəsaɪz/", "v. 强调"),
      w("encourage", "/ɪnˈkʌrɪdʒ/", "v. 鼓励"),
      w("environment", "/ɪnˈvaɪrənmənt/", "n. 环境"),
      w("essential", "/ɪˈsenʃl/", "adj. 必要的，本质的"),
      w("establish", "/ɪˈstæblɪʃ/", "v. 建立，确立"),
      w("estimate", "/ˈestɪmeɪt/", "v./n. 估计"),
      w("evidence", "/ˈevɪdəns/", "n. 证据"),
      w("expand", "/ɪkˈspænd/", "v. 扩大，膨胀"),
      w("frequent", "/ˈfriːkwənt/", "adj. 频繁的"),
      w("fundamental", "/ˌfʌndəˈmentl/", "adj. 基本的，根本的"),
      w("generate", "/ˈdʒenəreɪt/", "v. 产生，生成"),
      w("guarantee", "/ˌɡærənˈtiː/", "v./n. 保证"),
      w("hypothesis", "/haɪˈpɒθəsɪs/", "n. 假设"),
      w("identify", "/aɪˈdentɪfaɪ/", "v. 识别，确认"),
      w("impact", "/ˈɪmpækt/", "n. 影响，冲击"),
      w("implement", "/ˈɪmplɪment/", "v. 实施 n. 工具"),
      w("indicate", "/ˈɪndɪkeɪt/", "v. 表明，指示"),
      w("influence", "/ˈɪnfluəns/", "n./v. 影响"),
      w("involve", "/ɪnˈvɒlv/", "v. 涉及，使参与"),
      w("justify", "/ˈdʒʌstɪfaɪ/", "v. 证明…正当"),
      w("knowledge", "/ˈnɒlɪdʒ/", "n. 知识"),
      w("logic", "/ˈlɒdʒɪk/", "n. 逻辑"),
      w("maintain", "/meɪnˈteɪn/", "v. 维持，保养"),
      w("mechanism", "/ˈmekənɪzəm/", "n. 机制，原理"),
      w("negotiate", "/nɪˈɡəʊʃieɪt/", "v. 谈判，协商"),
      w("obtain", "/əbˈteɪn/", "v. 获得"),
      w("obvious", "/ˈɒbviəs/", "adj. 明显的"),
      w("occur", "/əˈkɜː/", "v. 发生，出现"),
      w("opportunity", "/ˌɒpəˈtjuːnəti/", "n. 机会"),
      w("participate", "/pɑːˈtɪsɪpeɪt/", "v. 参与"),
      w("phenomenon", "/fəˈnɒmɪnən/", "n. 现象"),
      w("policy", "/ˈpɒləsi/", "n. 政策，方针"),
      w("previous", "/ˈpriːviəs/", "adj. 先前的"),
      w("process", "/ˈprəʊses/", "n. 过程 v. 处理"),
      w("purchase", "/ˈpɜːtʃəs/", "v./n. 购买"),
      w("qualify", "/ˈkwɒlɪfaɪ/", "v. 使合格"),
      w("reduce", "/rɪˈdjuːs/", "v. 减少"),
      w("reluctant", "/rɪˈlʌktənt/", "adj. 不情愿的"),
      w("require", "/rɪˈkwaɪə/", "v. 需要，要求"),
      w("response", "/rɪˈspɒns/", "n. 回应，反应"),
      w("significant", "/sɪɡˈnɪfɪkənt/", "adj. 重要的，显著的"),
      w("source", "/sɔːs/", "n. 来源"),
      w("strategy", "/ˈstrætədʒi/", "n. 策略"),
      w("structure", "/ˈstrʌktʃə/", "n. 结构"),
      w("sufficient", "/səˈfɪʃnt/", "adj. 充足的"),
      w("tremendous", "/trəˈmendəs/", "adj. 巨大的"),
      w("ultimate", "/ˈʌltɪmət/", "adj. 最终的，根本的"),
      w("vague", "/veɪɡ/", "adj. 模糊的"),
      w("various", "/ˈveəriəs/", "adj. 各种各样的"),
      w("widespread", "/ˈwaɪdspred/", "adj. 广泛的"),
      w("yield", "/jiːld/", "v. 产出，屈服 n. 产量"),
      w("zealous", "/ˈzeləs/", "adj. 热心的，狂热的"),
    ],
  },
  {
    id: "cet6",
    name: "六级进阶",
    words: [
      w("abstract", "/ˈæbstrækt/", "adj. 抽象的 n. 摘要"),
      w("accelerate", "/əkˈseləreɪt/", "v. 加速"),
      w("accumulate", "/əˈkjuːmjəleɪt/", "v. 积累"),
      w("acknowledge", "/əkˈnɒlɪdʒ/", "v. 承认，致谢"),
      w("ambiguous", "/æmˈbɪɡjuəs/", "adj. 模棱两可的"),
      w("anticipate", "/ænˈtɪsɪpeɪt/", "v. 预期，期待"),
      w("apparatus", "/ˌæpəˈreɪtəs/", "n. 仪器，装置"),
      w("appraisal", "/əˈpreɪzl/", "n. 评估"),
      w("assess", "/əˈses/", "v. 评估"),
      w("assumption", "/əˈsʌmpʃn/", "n. 假设，设想"),
      w("attribute", "/əˈtrɪbjuːt/", "v. 归因于 n. 属性"),
      w("coherent", "/kəʊˈhɪərənt/", "adj. 连贯的，一致的"),
      w("compatible", "/kəmˈpætəbl/", "adj. 兼容的，相容的"),
      w("compelling", "/kəmˈpelɪŋ/", "adj. 令人信服的，引人入胜的"),
      w("comprehensive", "/ˌkɒmprɪˈhensɪv/", "adj. 全面的"),
      w("compromise", "/ˈkɒmprəmaɪz/", "n./v. 妥协"),
      w("conscientious", "/ˌkɒnʃiˈenʃəs/", "adj. 认真的，尽责的"),
      w("consensus", "/kənˈsensəs/", "n. 共识"),
      w("constraint", "/kənˈstreɪnt/", "n. 约束，限制"),
      w("contradict", "/ˌkɒntrəˈdɪkt/", "v. 反驳，矛盾"),
      w("controversial", "/ˌkɒntrəˈvɜːʃl/", "adj. 有争议的"),
      w("conventional", "/kənˈvenʃənl/", "adj. 传统的，常规的"),
      w("cumulative", "/ˈkjuːmjələtɪv/", "adj. 累积的"),
      w("deteriorate", "/dɪˈtɪəriəreɪt/", "v. 恶化"),
      w("discrepancy", "/dɪsˈkrepənsi/", "n. 差异，不一致"),
      w("dispute", "/dɪˈspjuːt/", "n./v. 争论"),
      w("diverse", "/daɪˈvɜːs/", "adj. 多样的"),
      w("dominant", "/ˈdɒmɪnənt/", "adj. 占主导的"),
      w("elaborate", "/ɪˈlæbərət/", "adj. 精心制作的 v. 详述"),
      w("endeavor", "/ɪnˈdevə/", "v./n. 努力，尽力"),
      w("enhance", "/ɪnˈhɑːns/", "v. 提高，增强"),
      w("explicit", "/ɪkˈsplɪsɪt/", "adj. 明确的，清晰的"),
      w("feasible", "/ˈfiːzəbl/", "adj. 可行的"),
      w("fluctuate", "/ˈflʌktʃueɪt/", "v. 波动"),
      w("formidable", "/ˈfɔːmɪdəbl/", "adj. 强大的，令人敬畏的"),
      w("hierarchy", "/ˈhaɪərɑːki/", "n. 等级制度"),
      w("hinder", "/ˈhɪndə/", "v. 阻碍"),
      w("implication", "/ˌɪmplɪˈkeɪʃn/", "n. 含意，影响"),
      w("incentive", "/ɪnˈsentɪv/", "n. 激励，动机"),
      w("inevitable", "/ɪnˈevɪtəbl/", "adj. 不可避免的"),
      w("inherent", "/ɪnˈhɪərənt/", "adj. 固有的，内在的"),
      w("initiative", "/ɪˈnɪʃətɪv/", "n. 主动性，倡议"),
      w("intrinsic", "/ɪnˈtrɪnsɪk/", "adj. 本质的，固有的"),
      w("legitimate", "/lɪˈdʒɪtɪmət/", "adj. 合法的，正当的"),
      w("meticulous", "/məˈtɪkjələs/", "adj. 一丝不苟的"),
      w("notable", "/ˈnəʊtəbl/", "adj. 显著的，值得注意的"),
      w("notorious", "/nəʊˈtɔːriəs/", "adj. 臭名昭著的"),
      w("paradox", "/ˈpærədɒks/", "n. 悖论"),
      w("perceive", "/pəˈsiːv/", "v. 感知，察觉"),
      w("persistent", "/pəˈsɪstənt/", "adj. 持续的，坚持的"),
      w("pragmatic", "/præɡˈmætɪk/", "adj. 务实的"),
      w("precise", "/prɪˈsaɪs/", "adj. 精确的"),
      w("profound", "/prəˈfaʊnd/", "adj. 深刻的，深远的"),
      w("prominent", "/ˈprɒmɪnənt/", "adj. 突出的，著名的"),
      w("provoke", "/prəˈvəʊk/", "v. 激起，挑衅"),
      w("redundant", "/rɪˈdʌndənt/", "adj. 多余的，冗余的"),
      w("refine", "/rɪˈfaɪn/", "v. 精炼，改进"),
      w("resilient", "/rɪˈzɪliənt/", "adj. 有韧性的，能恢复的"),
      w("rigorous", "/ˈrɪɡərəs/", "adj. 严格的，严谨的"),
      w("scrutiny", "/ˈskruːtəni/", "n. 仔细审查"),
      w("simultaneous", "/ˌsɪmlˈteɪniəs/", "adj. 同时的"),
      w("sophisticated", "/səˈfɪstɪkeɪtɪd/", "adj. 复杂精密的，老练的"),
      w("speculate", "/ˈspekjuleɪt/", "v. 推测，投机"),
      w("subtle", "/ˈsʌtl/", "adj. 微妙的，细微的"),
      w("sustainable", "/səˈsteɪnəbl/", "adj. 可持续的"),
      w("tedious", "/ˈtiːdiəs/", "adj. 乏味的，冗长的"),
      w("tentative", "/ˈtentətɪv/", "adj. 试探性的，暂定的"),
      w("transparent", "/trænsˈpærənt/", "adj. 透明的，清晰的"),
      w("trigger", "/ˈtrɪɡə/", "v. 触发 n. 扳机"),
      w("versatile", "/ˈvɜːsətaɪl/", "adj. 多才多艺的，多用途的"),
      w("viable", "/ˈvaɪəbl/", "adj. 可行的，能存活的"),
      w("vigorous", "/ˈvɪɡərəs/", "adj. 精力充沛的，强有力的"),
      w("vulnerable", "/ˈvʌlnərəbl/", "adj. 脆弱的，易受伤的"),
    ],
  },
  {
    id: "ielts",
    name: "雅思学术",
    words: [
      w("advocate", "/ˈædvəkeɪt/", "v. 提倡 n. 拥护者"),
      w("aggregate", "/ˈæɡrɪɡət/", "n. 总计 adj. 总的"),
      w("allocate", "/ˈæləkeɪt/", "v. 分配"),
      w("alleviate", "/əˈliːvieɪt/", "v. 减轻，缓解"),
      w("analogy", "/əˈnælədʒi/", "n. 类比，类推"),
      w("arbitrary", "/ˈɑːbɪtrəri/", "adj. 任意的，武断的"),
      w("coincide", "/ˌkəʊɪnˈsaɪd/", "v. 同时发生，一致"),
      w("compensate", "/ˈkɒmpenseɪt/", "v. 补偿"),
      w("compile", "/kəmˈpaɪl/", "v. 汇编，编辑"),
      w("comprise", "/kəmˈpraɪz/", "v. 包含，构成"),
      w("conceive", "/kənˈsiːv/", "v. 构想，怀孕"),
      w("constitute", "/ˈkɒnstɪtjuːt/", "v. 构成，组成"),
      w("contemporary", "/kənˈtemprəri/", "adj. 当代的"),
      w("correlate", "/ˈkɒrəleɪt/", "v. 相关联"),
      w("crucial", "/ˈkruːʃl/", "adj. 关键的"),
      w("derive", "/dɪˈraɪv/", "v. 源自，得到"),
      w("deviate", "/ˈdiːvieɪt/", "v. 偏离"),
      w("differentiate", "/ˌdɪfəˈrenʃieɪt/", "v. 区分"),
      w("diminish", "/dɪˈmɪnɪʃ/", "v. 减少，削弱"),
      w("distort", "/dɪˈstɔːt/", "v. 扭曲，歪曲"),
      w("disrupt", "/dɪsˈrʌpt/", "v. 扰乱，中断"),
      w("empirical", "/ɪmˈpɪrɪkl/", "adj. 经验主义的，实证的"),
      w("equivalent", "/ɪˈkwɪvələnt/", "adj. 等同的 n. 等价物"),
      w("evident", "/ˈevɪdənt/", "adj. 明显的"),
      w("exceed", "/ɪkˈsiːd/", "v. 超过"),
      w("exploit", "/ɪkˈsplɔɪt/", "v. 利用，开发"),
      w("expose", "/ɪkˈspəʊz/", "v. 暴露，揭露"),
      w("facilitate", "/fəˈsɪlɪteɪt/", "v. 促进，使便利"),
      w("formulate", "/ˈfɔːmjuleɪt/", "v. 制定，明确表达"),
      w("framework", "/ˈfreɪmwɜːk/", "n. 框架，体系"),
      w("highlight", "/ˈhaɪlaɪt/", "v. 强调 n. 亮点"),
      w("ideology", "/ˌaɪdiˈɒlədʒi/", "n. 意识形态"),
      w("implicit", "/ɪmˈplɪsɪt/", "adj. 含蓄的，隐含的"),
      w("incorporate", "/ɪnˈkɔːpəreɪt/", "v. 合并，纳入"),
      w("integral", "/ˈɪntɪɡrəl/", "adj. 不可或缺的"),
      w("integrate", "/ˈɪntɪɡreɪt/", "v. 整合，融合"),
      w("interpret", "/ɪnˈtɜːprɪt/", "v. 解释，口译"),
      w("intervene", "/ˌɪntəˈviːn/", "v. 干预，介入"),
      w("isolate", "/ˈaɪsəleɪt/", "v. 隔离"),
      w("manipulate", "/məˈnɪpjuleɪt/", "v. 操纵，操作"),
      w("methodology", "/ˌmeθəˈdɒlədʒi/", "n. 方法论"),
      w("notion", "/ˈnəʊʃn/", "n. 概念，观念"),
      w("objective", "/əbˈdʒektɪv/", "n. 目标 adj. 客观的"),
      w("ongoing", "/ˈɒnɡəʊɪŋ/", "adj. 持续进行的"),
      w("optimal", "/ˈɒptɪməl/", "adj. 最优的"),
      w("paradigm", "/ˈpærədaɪm/", "n. 范式，典范"),
      w("phenomena", "/fəˈnɒmɪnə/", "n. 现象（复数）"),
      w("plausible", "/ˈplɔːzəbl/", "adj. 似乎合理的"),
      w("predominant", "/prɪˈdɒmɪnənt/", "adj. 占主导地位的"),
      w("prevalent", "/ˈprevələnt/", "adj. 普遍的，流行的"),
      w("prioritize", "/praɪˈɒrɪtaɪz/", "v. 优先处理"),
      w("prohibit", "/prəˈhɪbɪt/", "v. 禁止"),
      w("proportion", "/prəˈpɔːʃn/", "n. 比例，部分"),
      w("reinforce", "/ˌriːɪnˈfɔːs/", "v. 加强，强化"),
      w("reluctance", "/rɪˈlʌktəns/", "n. 不情愿"),
      w("restrict", "/rɪˈstrɪkt/", "v. 限制"),
      w("retain", "/rɪˈteɪn/", "v. 保留，保持"),
      w("reveal", "/rɪˈviːl/", "v. 揭示"),
      w("rigid", "/ˈrɪdʒɪd/", "adj. 僵硬的，严格的"),
      w("scenario", "/səˈnɑːriəʊ/", "n. 情景，设想"),
      w("scope", "/skəʊp/", "n. 范围"),
      w("subsequent", "/ˈsʌbsɪkwənt/", "adj. 随后的"),
      w("substantial", "/səbˈstænʃl/", "adj. 大量的，重大的"),
      w("substitute", "/ˈsʌbstɪtjuːt/", "v./n. 替代（品）"),
      w("supplement", "/ˈsʌplɪmənt/", "n. 补充 v. 增补"),
      w("theoretical", "/ˌθɪəˈretɪkl/", "adj. 理论的"),
      w("threshold", "/ˈθreʃhəʊld/", "n. 门槛，临界点"),
      w("transition", "/trænˈzɪʃn/", "n. 过渡，转变"),
      w("underlying", "/ˌʌndəˈlaɪɪŋ/", "adj. 潜在的，根本的"),
      w("undermine", "/ˌʌndəˈmaɪn/", "v. 破坏，削弱"),
      w("undertake", "/ˌʌndəˈteɪk/", "v. 承担，从事"),
      w("uniform", "/ˈjuːnɪfɔːm/", "adj. 统一的 n. 制服"),
      w("validity", "/vəˈlɪdəti/", "n. 有效性，正当性"),
    ],
  },
  {
    id: "daily",
    name: "日常口语",
    words: [
      w("afford", "/əˈfɔːd/", "v. 买得起，负担得起"),
      w("appointment", "/əˈpɔɪntmənt/", "n. 约会，预约"),
      w("apologize", "/əˈpɒlədʒaɪz/", "v. 道歉"),
      w("aisle", "/aɪl/", "n. 过道，通道"),
      w("blanket", "/ˈblæŋkɪt/", "n. 毯子"),
      w("borrow", "/ˈbɒrəʊ/", "v. 借入"),
      w("budget", "/ˈbʌdʒɪt/", "n. 预算"),
      w("cancel", "/ˈkænsl/", "v. 取消"),
      w("ceiling", "/ˈsiːlɪŋ/", "n. 天花板"),
      w("charge", "/tʃɑːdʒ/", "v. 收费，充电 n. 费用"),
      w("commute", "/kəˈmjuːt/", "v. 通勤"),
      w("complain", "/kəmˈpleɪn/", "v. 抱怨，投诉"),
      w("convenient", "/kənˈviːniənt/", "adj. 方便的"),
      w("cozy", "/ˈkəʊzi/", "adj. 舒适温馨的"),
      w("decision", "/dɪˈsɪʒn/", "n. 决定"),
      w("deliver", "/dɪˈlɪvə/", "v. 递送，交付"),
      w("dessert", "/dɪˈzɜːt/", "n. 甜点"),
      w("discount", "/ˈdɪskaʊnt/", "n. 折扣"),
      w("downtown", "/ˌdaʊnˈtaʊn/", "n./adv. 市中心"),
      w("errand", "/ˈerənd/", "n. 差事，跑腿"),
      w("exhausted", "/ɪɡˈzɔːstɪd/", "adj. 筋疲力尽的"),
      w("familiar", "/fəˈmɪliə/", "adj. 熟悉的"),
      w("fare", "/feə/", "n. 车费，票价"),
      w("fridge", "/frɪdʒ/", "n. 冰箱"),
      w("furniture", "/ˈfɜːnɪtʃə/", "n. 家具"),
      w("groceries", "/ˈɡrəʊsəriz/", "n. 食品杂货"),
      w("guarantee", "/ˌɡærənˈtiː/", "n./v. 保修，保证"),
      w("hesitate", "/ˈhezɪteɪt/", "v. 犹豫"),
      w("hobby", "/ˈhɒbi/", "n. 爱好"),
      w("ingredient", "/ɪnˈɡriːdiənt/", "n. 原料，成分"),
      w("invoice", "/ˈɪnvɔɪs/", "n. 发票，账单"),
      w("itinerary", "/aɪˈtɪnərəri/", "n. 行程，路线"),
      w("laundry", "/ˈlɔːndri/", "n. 要洗的衣物，洗衣店"),
      w("leftover", "/ˈleftəʊvə/", "n. 剩饭剩菜 adj. 剩余的"),
      w("leisure", "/ˈleʒə/", "n. 闲暇，休闲"),
      w("luggage", "/ˈlʌɡɪdʒ/", "n. 行李"),
      w("microwave", "/ˈmaɪkrəweɪv/", "n. 微波炉"),
      w("neighbor", "/ˈneɪbə/", "n. 邻居"),
      w("nervous", "/ˈnɜːvəs/", "adj. 紧张的"),
      w("notice", "/ˈnəʊtɪs/", "v. 注意到 n. 通知"),
      w("opportunity", "/ˌɒpəˈtjuːnəti/", "n. 机会"),
      w("oven", "/ˈʌvn/", "n. 烤箱"),
      w("parcel", "/ˈpɑːsl/", "n. 包裹"),
      w("pharmacy", "/ˈfɑːməsi/", "n. 药房"),
      w("polite", "/pəˈlaɪt/", "adj. 礼貌的"),
      w("postpone", "/pəˈspəʊn/", "v. 推迟"),
      w("purchase", "/ˈpɜːtʃəs/", "v./n. 购买"),
      w("queue", "/kjuː/", "n. 队列 v. 排队"),
      w("receipt", "/rɪˈsiːt/", "n. 收据"),
      w("recommend", "/ˌrekəˈmend/", "v. 推荐"),
      w("refund", "/ˈriːfʌnd/", "n./v. 退款"),
      w("relax", "/rɪˈlæks/", "v. 放松"),
      w("rent", "/rent/", "v. 租 n. 租金"),
      w("reserve", "/rɪˈzɜːv/", "v. 预订，保留"),
      w("schedule", "/ˈʃedjuːl/", "n. 日程 v. 安排"),
      w("souvenir", "/ˌsuːvəˈnɪə/", "n. 纪念品"),
      w("spicy", "/ˈspaɪsi/", "adj. 辛辣的"),
      w("stuck", "/stʌk/", "adj. 卡住的，困住的"),
      w("suggest", "/səˈdʒest/", "v. 建议"),
      w("traffic", "/ˈtræfɪk/", "n. 交通"),
      w("umbrella", "/ʌmˈbrelə/", "n. 雨伞"),
      w("vacancy", "/ˈveɪkənsi/", "n. 空缺，空房"),
      w("vacuum", "/ˈvækjuːm/", "v. 用吸尘器打扫 n. 真空"),
      w("weather", "/ˈweðə/", "n. 天气"),
      w("wallet", "/ˈwɒlɪt/", "n. 钱包"),
      w("warranty", "/ˈwɒrənti/", "n. 保修单，保证"),
      w("worth", "/wɜːθ/", "adj. 值得的 n. 价值"),
    ],
  },
];

/** 全部单词扁平列表（向后兼容）。 */
export const WORDBANK: WordEntry[] = LEVELS.flatMap((l) => l.words);
